export const ROUTES = {
	LOGIN: '/login',
	PROFILE: '/profile',
	PROPERTIES: '/properties',
	ADDPROPERTY: 'add-property',
	USERS: '/users',
	CUSTOMERS: '/customers',
	ORDERS: '/orders',
	COMPANY: '/company',
	SUPPORT: '/support',
	DETAILS: '/details',
	SUPPORTLIST: '/support-list',
	REALTORS: '/realtors',
	PROPERTYDETAILS: '/property-details',
} as const;
